Repository LightBitsLabs/los-csi, pull requests merged in 2025-06, with the labels that each got.

#81 bump csi script
  scripts/bump-csi-version.sh
Labels: enhancement, m1, feat:k8s, infra

#82 Makefile: delete helm templates of old deprecated csi versions
  Makefile
Labels: enhancement, main, feat:k8s, m4

#86 lb-csi-attacher-cluster-role.yaml: rename external-attacher-runner ba…
  deploy/helm/lb-csi/templates/lb-csi-attacher-cluster-role.yaml
Labels: bug, m1, main

#79 fix: explicitly specify fsType in StorageClass example template
  deploy/helm/lb-csi-workload-examples/values.yaml
Labels: bug, m1, main
